### ISSUE TITLE
psad not working on ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by mme89** [mrash/psad#73]
hi,
yesterday I updated to Ubuntu 20.04 LTS and I can't get PSAD to work anymore.
Tried both variants to install via apt-get and via install.pl. The errors resulting are similar.

`Would you like to install the latest signatures from
      http://www.cipherdyne.org/psad/signatures (y/n)?  y
[+] CMD: '/usr/sbin/psad --sig-update'
Can't load '/usr/lib/psad/x86_64-linux-gnu-thread-multi/auto/Date/Calc/Calc.so' for module Date::Calc: /usr/lib/psad/x86_64-linux-gnu-thread-multi/auto/Date/Calc/Calc.so: undefined symbol: DateCalc_Day_of_Week_to_Text_ at /usr/lib/x86_64-linux-gnu/perl/5.30/DynaLoader.pm line 193.
 at /usr/sbin/psad line 3302.
Compilation failed in require at /usr/sbin/psad line 3302.`

`Would you like to install the latest reputation feed data (y/n)?  y
[+] CMD: '/usr/sbin/psad --reputation-feeds-update'
Can't load '/usr/lib/psad/x86_64-linux-gnu-thread-multi/auto/Date/Calc/Calc.so' for module Date::Calc: /usr/lib/psad/x86_64-linux-gnu-thread-multi/auto/Date/Calc/Calc.so: undefined symbol: DateCalc_Day_of_Week_to_Text_ at /usr/lib/x86_64-linux-gnu/perl/5.30/DynaLoader.pm line 193.
 at /usr/sbin/psad line 3302.
Compilation failed in require at /usr/sbin/psad line 3302.`

anyone noticed the same behavior?

**Comment by libellux** [comment]
@teminvictus I receive the following issue when trying to build 2.4.6 from source (however apt-get works for me but version 2.4.3):

`[*] Could not copy psadwatchd -> /usr/sbin/psadwatchd: No such file or directory at ./install.pl line 516.`

**Comment by mme89** [comment]
I looked a little more into it. Using the latest GitHub version, the same error still comes up.
But I managed to get it working.

This error comes up in all situations:

`Compilation failed in require at /usr/sbin/psad line 3302`

I looked in line 3302 and uncomment this line:

`#    require Date::Calc;`

This at least makes psad work again. Not sure what the consequences are, but till now everything seems to be working.

**Comment by libellux** [comment]
I tried again today and successfully I did not have to ucomment the line 3302 @teminvictus all I had to do was install the dependencies contained in `net-tools` and `g++`.

**Comment by mme89** [comment]
@libellux , thanks.

For now my solution seems to work, psad is doing everything normal.
I will keep monitoring it.
